import { defineConfig } from "oxlint"
import core from "ultracite/oxlint/core"

export default defineConfig({
  extends: [core],
  ignorePatterns: [
    "**/dist/**",
    "**/build/**",
    "**/.nx/**",
    "**/.output/**",
    "**/node_modules/**",
    "**/coverage/**",
    "**/repos/**",
    "**/routeTree.gen.ts",

    // Nx AI-agent config artifacts (only keep .agents standards in repo)
    "**/.agents/**",
  ],
  rules: {
    // Keep Ultracite base, but relax repo-breaking rules to match existing codebase.
    "eslint/func-style": "off",
    "eslint/no-nested-ternary": "off",
    "eslint/no-use-before-define": "off",
    "eslint/require-await": "off",
    "eslint/sort-keys": "off",
    "import/consistent-type-specifier-style": "off",
    "oxc/no-barrel-file": "off",
    "typescript/consistent-type-definitions": "off",
    "unicorn/filename-case": "off",
    "unicorn/no-document-cookie": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/prefer-import-meta-properties": "off",

    "eslint/arrow-body-style": "off",
    "eslint/curly": "off",
    "eslint/func-names": "off",
    "eslint/no-empty-function": "off",
    "eslint/require-unicode-regexp": "off",
    "typescript/ban-types": "off",
    "typescript/consistent-indexed-object-style": "off",
    "unicorn/prefer-dom-node-dataset": "off",

    "typescript/consistent-type-imports": [
      "error",
      { fixStyle: "inline-type-imports" },
    ],
    "typescript/no-import-type-side-effects": "error",
    "import/no-duplicates": "error",
    "import/no-self-import": "error",
    "import/no-empty-named-blocks": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-useless-empty-export": "error",
    "eslint/no-console": "error",
    "eslint/no-var": "error",
    "eslint/no-useless-constructor": "error",
    "unicorn/no-abusive-eslint-disable": "error",
    "eslint/no-unneeded-ternary": "error",
    "eslint/no-useless-concat": "error",
    "oxc/misrefactored-assign-op": "error",
    "unicorn/prefer-array-flat-map": "error",
    "unicorn/no-accessor-recursion": "error",

    "oxc/no-map-spread": "off",
    "eslint/object-shorthand": "off",
    "eslint/no-unused-vars": "off",
    "eslint/require-yield": "off",
    "eslint/no-fallthrough": "off",
    "eslint/no-await-in-loop": "off",
    "unicorn/no-new-array": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/no-array-reverse": "off",
    "unicorn/require-post-message-target-origin": "off",
    "unicorn/prefer-add-event-listener": "off",
    "unicorn/prefer-set-has": "off",
    "typescript/no-explicit-any": "off",
    "typescript/no-empty-interface": "off",
    "typescript/ban-ts-comment": "off",
    "typescript/no-namespace": "off",
    "typescript/no-non-null-assertion": "off",
    "typescript/no-dynamic-delete": "off",
    "typescript/no-invalid-void-type": "off",
    "typescript/no-unsafe-function-type": "off",
    "typescript/unified-signatures": "off",
    "typescript/no-empty-object-type": "off",
    "typescript/no-confusing-non-null-assertion": "off",

    "typescript/array-type": [
      "error",
      { default: "generic", readonly: "generic" },
    ],
    "typescript/no-unused-vars": [
      "error",
      { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
    ],
  },
})
